project:
  type: website
  output-dir: ../html
  preview:
    port: 4200
  resources:
    - "/_redirects"

website:
  title: "bit-server"
  image: "server.png"
  favicon: "favicon.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://r2bit.ddns.net
  repo-url: https://github.com/joygram/bit-server
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    algolia:
      index-name: prod_QUARTO
      application-id: ZPJB5I1QN7
      search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      analytics-events: true
      show-logo: true

  page-footer:
    left: |
      Supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://r2bit.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: link
        href: https://joygram.info
        aria-label: joygram.info
      - icon: github
        href: https://github.com/joygram/bit-server
        aria-label: joygram's GitHub

  navbar:
    background: dark
    logo: server.png
    logo-alt: "bit-server logo."
    title: false
    collapse-below: lg
    left:
      - text: "둘러보기"
        href: index.qmd
      - text: "시작하기"
        href: docs/get-started/index.qmd
      - text: "가이드"
        href: docs/guide/index.qmd
      - text: "프레젠테이션"
        href: docs/gallery/index.qmd
      - text: "디지털 글쓰기"
        href: docs/digitalwriting/index.qmd

    right:
      - icon: link
        href: https://r2bit.com
        aria-label: r2bit
      - icon: github
        href: https://github.com/joygram/bit-server
        aria-label: bit-server GitHub

  sidebar:
    - id: get-started
      title: "시작해보기"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/get-started/index.qmd
        - text: "- Hello, bit-server"
          href: docs/get-started/hello/
        - text: "- 작업 환경(Workspace)"
          href: docs/get-started/computations/
        - text: "- 저작 활동(Authoring)"
          href: docs/get-started/authoring/

    - id: guide
      collapse-level: 1
      contents:
        - text: "Guide"
          href: docs/guide/index.qmd
        - section: "Authoring"
          contents:
            - docs/authoring/markdown-basics.qmd
        - section: "Presentations"
          contents:
            - text: "Overview"
              href: docs/presentations/index.qmd
 
bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - quarto

freeze: true

editor: visual
