project:
  type: website
  output-dir: ../html
  preview:
    port: 4200
  resources:
    - "/_redirects"

website:
  title: "bit-server"
  image: "server.png"
  favicon: "favicon.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://bit2edu.ddns.net
  repo-url: https://github.com/joygram/bit-server
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    algolia:
      index-name: prod_QUARTO
      application-id: ZPJB5I1QN7
      search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      analytics-events: true
      show-logo: true

  page-footer:
    left: |
      Supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://r2bit.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: link
        href: https://bit2edu.ddns.net
        aria-label: bit2edu.ddns.net
      - icon: github
        href: https://github.com/joygram/bit-server
        aria-label: joygram's GitHub

  navbar:
    background: dark
    logo: server.png
    logo-alt: "bit-server logo."
    title: false
    collapse-below: lg
    left:
      - text: "시작하기"
        href: docs/get-started/index.qmd
      - text: "통계와 디지털글쓰기"
        href: docs/stat-edu/index.qmd
      - text: "어플리케이션"
        menu:
          - text: "통계패키지"
            href: /app/bitStat/
          - text: "디지털 글쓰기"
            icon: "pencil"
            href: docs/digitalwriting/index.qmd
          - text: "reeborg's world"
            icon: "code-square"
            href: /app/reeborg/
          - text: "RStudio"
            icon: "code"
            href: /rstudio/


    right:
      - icon: link
        href: https://r2bit.com
        aria-label: r2bit
      - icon: github
        href: https://github.com/joygram/bit-server
        aria-label: bit-server GitHub
  sidebar:
    - id: guide
      collapse-level: 1
      contents:
        - text: "통계교육과 디지털 글쓰기"
          href: docs/guide/index.qmd
        - section: "통계교육과 디지털 글쓰기"
          contents:
            - docs/stat-edu/수학통계교육의고찰.qmd
            - docs/stat-edu/온-오프라인의연계방안.qmd
            - /app/digital-writing/

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - quarto

freeze: true

editor: visual
